---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.4

suites:
  - name: files
    run_list:
      - recipe[nmd-drupal::files]
    attributes:
