---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04-vmware
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: ubuntu-14.04-virtualbox
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: centos-6.5-vmware
    driver_config:
      box: centos-6.5
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
  - name: centos-6.5-virtualbox
    driver_config:
      box: centos-6.5
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
suites:
  - name: default
    run_list:
      - recipe[git::default]
      - recipe[mysql::server]
      - recipe[nmddrupal::drush]
      - recipe[nmddrupal::files]
      - recipe[nmddrupal::deploy_code]
  - name: deploy-drush
    run_list:
      - recipe[nmddrupal::deploy_drush]
  - name: delete-drush
    run_list:
      - recipe[nmddrupal::deploy_drush]
      - recipe[nmddrupal::delete_drush]
  - name: files
    run_list:
      - recipe[nmddrupal::files]
  - name: deploy-code
    run_list:
      - recipe[nmddrupal::deploy_code]
  - name: delete-code
    run_list:
      - recipe[nmddrupal::deploy_code]
      - recipe[nmddrupal::delete_code]
  - name: deploy-mysql
    run_list:
      - recipe[mysql::server]
      - recipe[nmddrupal::deploy_mysql]
  - name: delete-mysql
    run_list:
      - recipe[mysql::server]
      - recipe[nmddrupal::deploy_mysql]
      - recipe[nmddrupal::delete_mysql]
