---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04-vmware
    driver_config:
      box: ubuntu-12.04
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-x86_64-base.box
  - name: ubuntu-12.04-virtualbox
    driver_config:
      box: ubuntu-12.04
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-12.04-x86_64-base.box
  - name: ubuntu-14.04-vmware
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: ubuntu-14.04-virtualbox
    driver_config:
      box: ubuntu-14.04
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-ubunutu-14.04-x86_64-base.box
  - name: centos-6.5-vmware
    driver_config:
      box: centos-6.5
      box_url: https://nmd-vmware.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
  - name: centos-6.5-virtualbox
    driver_config:
      box: centos-6.5
      box_url: https://nmd-virtualbox.s3-us-west-2.amazonaws.com/nmd-centos-6.5-x86_64-base.box
suites:
  - name: default
    run_list:
      - recipe[nmd-drupal::drush]
      - recipe[nmd-drupal::files]
    attributes:
  - name: drush
    run_list:
      - recipe[git::default]
      - recipe[nmd-drupal::drush]
    attributes:
  - name: files
    run_list:
      - recipe[nmd-drupal::files]
    attributes:
